name: Publish to another (Prod) repository

on:
  push:
    tags:        
      - '**' # Triggers on all tags

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4  # Updated to latest version
      
      - name: Setup Node
        uses: actions/setup-node@v4  # Updated to Node setup version
        with:
          node-version: "20"
          cache: npm

      - name: Install dependencies
        run: npm install --legacy-peer-deps

      - name: Build with Next.js for production
        run: |
          echo "Building with base path for production"
          NEXT_PUBLIC_BASE_PATH=/gfk-prod npm run build

      - name: Check build output
        run: |
          if [ ! -d "out" ]; then
            echo "Error: 'out' directory not found"
            echo "Current directory contents:"
            ls -la
            exit 1
          fi
          
      - name: Show build files in output directory   
        run: ls -la out

      - name: Push build artifacts to another repository
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source-directory: 'out'  # Directory containing build artifacts
          destination-github-username: 'HunterGerlach'
          destination-repository-name: 'gfk-prod'
          user-email: hunter@huntergerlach.com
          target-branch: main
