name: Deploy Next.js site to Pages

on:
  push:
    branches: ["staging"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: npm
      - name: Setup Pages
        uses: actions/configure-pages@v3
        with:
          static_site_generator: next
      - name: Install dependencies
        run: npm install --legacy-peer-deps

      - name: Build with Next.js
        run: NEXT_NO_TURBOPACK=1 npm run build

      # Debugging: Check contents after build
      - name: Confirm .next and out directories
        run: |
          echo "Listing root directory:"
          ls -la
          echo "Listing .next directory contents:"
          ls -la .next || echo "No .next directory found"
          echo "Listing out directory contents:"
          ls -la out || echo "No out directory found"

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./out

  deploy:
    environment:
      name: github-pages-staging
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages Staging Environment
        id: deployment
        uses: actions/deploy-pages@v1
